/**
 * `raghub init` — local-first wizard.
 *
 * Phase 1 writes a `.env.example`-style config file (`.raghub/.env`)
 * with sane defaults. Phase 2 wires the interactive prompts (mode,
 * hybrid weights, ordering, k, reranker, multimodal, trace corpus).
 *
 * In the meantime, the wizard writes a default config and prints the
 * next-step hints.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import type { Command } from '../runner.js';

const DEFAULT_ENV = `# Generated by \`raghub init\`.

RAGHUB_JWT_SECRET=replace-me-with-32-plus-chars-of-randomness
RAGHUB_TENANT_SECRETS_KEY=replace-me-with-64-hex-chars-of-randomness

# LLM + embedding
OPENAI_API_KEY=
RAGHUB_LLM_MODEL=gpt-4.1
RAGHUB_EMBEDDER_MODEL=text-embedding-3-large

# Vector store (sqlite-vec only)
RAGHUB_VECTOR_BACKEND=sqlite_vec
RAGHUB_VECTOR_PATH=./.raghub/raghub.db
RAGHUB_VECTOR_EMBEDDING_DIM=3072

# Orchestrator
RAGHUB_ORCHESTRATOR_MODE=graph
RAGHUB_ORCHESTRATOR_ORDERING=standard
RAGHUB_ORCHESTRATOR_TOP_K=10
RAGHUB_ORCHESTRATOR_RERANKER=identity

# Hybrid retrieval
RAGHUB_HYBRID_DENSE_WEIGHT=0.6
RAGHUB_HYBRID_SPARSE_WEIGHT=0.4
RAGHUB_HYBRID_RRF_K=60

# Telemetry
RAGHUB_TELEMETRY_PROVIDER=noop
`;

export const initCommand: Command = {
  name: 'init',
  description: 'Initialise a new raghub project (writes .raghub/.env).',
  usage: 'raghub init [--dir <path>]',
  async run({ flags, cwd }) {
    const dirRaw = flags['dir'];
    const dir = typeof dirRaw === 'string' ? dirRaw : cwd;
    const target = join(dir, '.raghub');
    await mkdir(target, { recursive: true });
    await writeFile(join(target, '.env'), DEFAULT_ENV, { mode: 0o600 });
    console.log(`✓ wrote ${join(target, '.env')}`);
    console.log('\nNext:');
    console.log('  1. edit .raghub/.env (set OPENAI_API_KEY + secrets)');
    console.log('  2. `raghub dev` to start the API + UI together');
    return 0;
  },
};