/**
 * Default agent implementations — planner / retriever / generator.
 *
 * These are the minimum Phase 1 ships; each is replaceable through
 * `AgentRegistry.register()`. Phase 2 adds CARE-aware retriever,
 * T3 trace-reasoner, multimodal-synthesizer, and the CARE judge.
 */

import { RaghubError, Retrieval, type Hit, User } from '@raghub/core';

import type { Agent } from './registry.js';
import type { InvocationState, OrchestratorRequest } from '../strands/types.js';

export const createRetrieverAgent = (retrieval: Retrieval): Agent => ({
  id: 'retriever',
  async retrieve(req, state) {
    if (!state.user_id) {
      return {
        ok: false,
        content: 'no authenticated user in invocation state',
        hits: [],
        latencyMs: 0,
      };
    }
    const start = Date.now();
    try {
      const { User } = await import('@raghub/core');
      const user = new User({
        id: state.user_id,
        tenantId: state.tenant_id,
        email: '',
        role: state.is_admin ? 'admin' : 'member',
        allowedCompanies: state.rbac_filter.allowedCompanies,
        createdAt: new Date(),
      });
      const hits = await retrieval.retrieve(user, req.question, state.strategy.k);
      return {
        ok: true,
        content: JSON.stringify(hits.map((h: Hit) => ({ id: h.chunk.id, score: h.score }))),
        hits,
        latencyMs: Date.now() - start,
      };
    } catch (e) {
      return {
        ok: false,
        content: e instanceof Error ? e.message : String(e),
        hits: [],
        latencyMs: Date.now() - start,
      };
    }
  },
  async generate() {
    throw new RaghubError('pipeline_error', 'retriever agent cannot generate');
  },
});

export const createGeneratorAgent = (): Agent => ({
  id: 'generator',
  async retrieve() {
    throw new RaghubError('pipeline_error', 'generator agent cannot retrieve');
  },
  async generate(req, hits, _state) {
    const start = Date.now();
    const context = hits
      .slice(0, 5)
      .map((h, i) => `[${i + 1}] ${h.chunk.text}`)
      .join('\n');
    const answer = `Based on ${hits.length} retrieved chunk(s), the answer is not yet generated by an LLM. Context:\n\n${context}\n\nQuestion: ${req.question}`;
    return { answer };
    void start;
  },
});